package com.fintrack.auth.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA entity representing OAuth2 linked accounts.
 *
 * <p>Allows users to authenticate via third-party social providers (Google, GitHub, etc.).
 * Each account is linked to a single {@link User} via a physical Foreign Key.
 *
 * <p>Table: {@code accounts}
 * <p>Unique constraint: {@code user_id + provider + provider_account_id}
 *
 * @author FinTrack Team
 * @since 1.0.0
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
@Entity
@Table(
    name = "accounts",
    indexes = {
        @Index(name = "idx_accounts_user_id", columnList = "user_id"),
        @Index(name = "idx_accounts_provider", columnList = "provider"),
        @Index(name = "idx_accounts_provider_account_id", columnList = "provider_account_id"),
        @Index(
            name = "idx_accounts_user_provider_unique",
            columnList = "user_id,provider,provider_account_id",
            unique = true
        )
    }
)
public class Account {

    /**
     * Primary key — UUID generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, length = 36)
    private String id;

    /**
     * The {@link User} this account is linked to.
     * Physical Foreign Key — enforces referential integrity at the database level.
     */
    @NotNull(message = "User cannot be null")
    @ManyToOne(optional = false)
    @JoinColumn(
        name = "user_id",
        nullable = false,
        foreignKey = @ForeignKey(name = "fk_accounts_user_id")
    )
    private User user;

    /**
     * OAuth2 provider name (e.g., "google", "github", "facebook").
     * Case-sensitive and normalized to lowercase.
     */
    @NotBlank(message = "Provider cannot be blank")
    @Column(name = "provider", nullable = false, length = 50)
    private String provider;

    /**
     * Provider-specific account ID (e.g., Google's "123456789" or GitHub's "1234567").
     * Unique per provider, but different providers may issue the same ID.
     */
    @NotBlank(message = "Provider account ID cannot be blank")
    @Column(name = "provider_account_id", nullable = false, length = 255)
    private String providerAccountId;

    /**
     * OAuth2 access token issued by the provider.
     * Used to make API calls on behalf of the user (e.g., fetch user profile, send emails).
     * Should be encrypted at rest if sensitive operations are performed.
     *
     * <p><b>Note:</b> Consider implementing token refresh logic and secure storage (e.g., encryption).
     */
    @NotNull(message = "Access token cannot be null")
    @Column(name = "access_token", nullable = false, columnDefinition = "TEXT")
    private String accessToken;
}

