package com.fintrack.core.base;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Base entity for all JPA entities in FinTrack.
 *
 * <p>Provides common audit fields automatically populated by Spring Data JPA
 * auditing ({@code @EnableJpaAuditing} must be enabled on each service's main class).
 *
 * <p><b>Soft delete:</b> Use {@code deleted = true} instead of physically removing
 * rows to preserve audit trails. Always filter by {@code deleted = false}
 * in repository queries.
 *
 * <p>Usage:
 * <pre>{@code
 * @Entity
 * @Table(name = "transactions")
 * public class Transaction extends BaseEntity {
 *     private BigDecimal amount;
 *     // ...
 * }
 * }</pre>
 *
 * @author FinTrack Team
 * @since 1.0.0
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /** Primary key — UUID generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, length = 36)
    private String id;

    /** Timestamp when this row was first inserted. Auto-set by JPA auditing. */
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update. Auto-updated by JPA auditing. */
    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * ID of the user who created this row.
     * Requires an {@code AuditorAware<String>} bean in each service.
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 36)
    private String createdBy;

    /**
     * ID of the user who last modified this row.
     * Requires an {@code AuditorAware<String>} bean in each service.
     */
    @LastModifiedBy
    @Column(name = "updated_by", length = 36)
    private String updatedBy;

    /**
     * Soft-delete flag. When {@code true}, this row is considered deleted
     * and should be excluded from query results.
     *
     * <p>Never set this directly — use the service layer's {@code delete()} method.
     */
    @Column(name = "is_deleted", nullable = false)
    private boolean deleted = false;
}
